config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'profile' => 'users#show', as: 'current_user'

  root 'application#root'
  get 'home' => 'static#home'

  get 'sessions/new'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new', as: 'login'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'dashboard' => 'dashboard#overview', as: 'dashboard'
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create { generate_token(:auth_token) }

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  validates :password, length: { minimum: 6 }, allow_blank: true

  has_secure_password

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def root
    if logged_in?
      redirect_to dashboard_path
    else
      redirect_to home_path
    end
  end

  def authenticate
    unless logged_in?
      redirect_to login_path
    end
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate

  before_action :set_user

  def overview
  end

  private
  def set_user
    @user = current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:sessions][:email].downcase)
    if user && user.authenticate(params[:sessions][:password])
      log_in(user,params[:sessions][:remember_me])
      redirect_to dashboard_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    flash[:success] = 'Logout successful'
    redirect_to root_url
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html {
          log_in(@user, true)
          flash[:success] = "#{@user.name}, your profile has been created"
          redirect_to dashboard_path
        }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  private
  def set_user
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user, remember_me)
    if remember_me == '1'
      cookies.permanent[:auth_token] = user.auth_token
    else
      cookies[:auth_token] = user.auth_token
    end
  end

  def current_user
    @current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    cookies.delete(:auth_token)
    @current_user = nil
  end

end

app/views/dashboard/overview.html.erb
Welcome, <%= @user.name %>

app/views/home/index.html.erb
Hello world

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Meetorite</a>
    </div>
    <p class="navbar-text pull-right">
    <ul class="nav navbar-nav navbar-right collapse navbar-collapse">
      <li><%= link_to "Home", root_path %></li>
      <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= @user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Profile", current_user_path %></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
      <% else %>
          <li><%= link_to "Log in", login_path, id: 'login' %></li>
          <li><%= link_to "Sign up", signup_path, id: 'signup' %></li>
      <% end %>
    </ul>

  </div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %> text-center"><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meetorite</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>

<%= render 'layouts/messages' %>
<div class="container">
  <%= yield %>
</div>


</body>
</html>

app/views/shared/_user_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <%= pluralize(@user.errors.count, "error") %> encountered, please rectify
      </div>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/new.html.erb
<div class="border-form-div">
  <h2>Sign up</h2>
  <%= form_for(@user) do |f| %>
      <%= render 'shared/user_error_messages' %>
      <%= f.email_field :email, :autofocus => true, :placeholder => 'Email address', :class => 'col-md-12 form-control' %>
      <%= f.text_field :name, :placeholder => 'Name', :class => 'col-md-12 form-control' %>
      <%= f.password_field :password, :placeholder => 'Password', :class => 'col-md-12 form-control' %>
      <%= f.password_field :password_confirmation, :placeholder => 'Password confirmation', :class => 'col-md-12 form-control' %>
      <%= f.submit "Sign up", :class => 'btn btn-primary' %>
  <% end %>
</div>

app/views/users/show.html.erb
<%= @user.name %>'s profile